steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/education-298320/nlp:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/education-298320/nlp', '--cache-from', 'gcr.io/education-298320/nlp:latest', '.']
images: ['gcr.io/education-298320/nlp:latest']