
# https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/projects.jobs#TrainingInput
trainingInput:
  # cheapest
  # scaleTier: BASIC

  # https://cloud.google.com/ai-platform/training/docs/reference/rest/v1/projects.jobs#scaletier
  scaleTier: CUSTOM
  # https://cloud.google.com/compute/docs/machine-types
  # https://cloud.google.com/compute/docs/gpus#a100-gpus
  masterType: n1-standard-4  # 6.5GB memory per CPU
  masterConfig:
    acceleratorConfig:
      count: 1
      # https://cloud.google.com/ai-platform/training/docs/using-gpus
      # https://cloud.google.com/compute/docs/gpus#gpu_comparison_chart
      type: NVIDIA_TESLA_K80 # $0.45 per hour per GPU | 12GB memory | 4.4 TFLOPS@FP32 (max batch size = )
      # type: NVIDIA_TESLA_V100 # $2.48 per hour per GPU | 16GB memory | 15.7 TFLOPS@FP32
      # type: NVIDIA_A100  # $3.1 per hour per GPU | 40GB memory | 19.5 TFLOPS@FP32 (requires A2 machine type)
      # TPUS are $8 per TPU per hour